- name: AMI search
  hosts: localhost
  gather_facts: false
  tasks:
    - name: search for existing AMI
      amazon.aws.ec2_ami_info:
        owners: ['amazon']
      register: ami_found

    - name: debug
      debug:
        var: ami_found
