---
- name: Launch EC2 instance with a public IP
  hosts: localhost
  gather_facts: false
  collections:
    - amazon.aws

  vars:
    aws_region: ap-south-1

  tasks:
    - name: Start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "home-mumbai"
        vpc_subnet_id: subnet-037d62220ca04ba91    # Updated subnet ID
        instance_type: t2.micro
        aws_secret_key: "{{ aws_secret_key }}"
        aws_access_key: "{{ aws_access_key }}"
        region: "{{ aws_region }}"
        network:
          assign_public_ip: true
          security_groups:  
            - sg-01db03566a339125f 
        image_id: ami-0f918f7e67a3323f0
        tags:
          Environment: Testing
      register: ec2_result

    - name: Print instance info
      debug:
        var: ec2_result

  
